name: ManhuntPlus
version: '${version}'
main: net.tutla.manhuntPlus.bootstrap.ManhuntPlusPlugin
api-version: '1.21'
authors: [ TutlaMC ]
website: https://tutla.net
permissions:
  manhuntplus.admin:
    description: "Administrative access to setup and control commands"
    default: op
  manhuntplus.play:
    description: "Gameplay command access"
    default: true
commands:
  compass:
    description: Gives a tracking compass
    usage: /<command> <player>
    permission: manhuntplus.play
  twist:
    description: Changes the twist
    usage: /<command> <twist>
    permission: manhuntplus.admin
  speedrunner:
    description: Add or remove a runner
    usage: /<command> add|remove <player>
    permission: manhuntplus.admin
  hunter:
    description: Add/remove a hunter
    usage: /<command> add|remove <player>
    permission: manhuntplus.admin
  manhunt:
    description: Start/stop/set cooldown/prepare
    usage: /<command> start|stop|cooldown|help|prepare|list
    permission: manhuntplus.admin
  surround:
    description: Surround a speedrunner with hunters
    usage: /<command> <player>
    permission: manhuntplus.admin
  randomvillage:
    description: Teleport near the nearest random village type
    usage: /<command>
    permission: manhuntplus.admin

